### ISSUE TITLE
[meta] Datasets

### ISSUE THREAD

**Issue by stites** [stites/hasklearn#2]
awkward spec for downloading datasets:

### Datasets.Download
- [ ] dir (show, clear, set)
- [ ] download link, download md5 (or do we lock this down?) (do we add a progress bar?)
- [ ] load (load with hmatrix, accelerate, data.vector? there is no "standard" that haskellers work off of)

### Datasets (mostly inspired by sklearn)
- [ ] 20 newsgroups dataset.
- [ ] California housing dataset from StatLib.
- [ ] kddcup 99 dataset (classification).
- [ ] Labeled Faces in the Wild (LFW) pairs dataset
- [ ] Labeled Faces in the Wild (LFW) people dataset
- [ ] Olivetti faces data-set from AT&T.
- [ ] RCV1 multilabel dataset
- [ ] species distribution dataset from Phillips et.
- [ ] boston house-prices dataset (regression).
- [ ] breast cancer wisconsin dataset (classification).
- [ ] diabetes dataset (regression).
- [ ] digits dataset (classification) MNIST?
- [x] iris dataset (classification).
- [ ] linnerud dataset (multivariate regression).
- [ ] wine dataset (classification).
